language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  - openjdk6
notifications:
  email: false
before_install:
  - git submodule update --init --recursive
  - git clone --depth=50 --branch=automated_authentication git://github.com/raptortech-js/jumblr.git jumblr
  - cp -R jumblr/src .
  - ls
  - ls src
